package network

import (
	"fmt"
	"net"
	"os"
	"strings"
)

const (
	resolvConf   = "/etc/resolv.conf"
	resolvBackup = "/etc/resolv.conf.pvpn.bak"
)

// DirectBackend manages DNS by directly writing /etc/resolv.conf.
// This is the fallback when neither NetworkManager nor systemd-resolved is available.
type DirectBackend struct {
	backedUp bool
}

// NewDirectBackend creates a direct DNS backend.
func NewDirectBackend() *DirectBackend {
	return &DirectBackend{}
}

func (b *DirectBackend) Name() string {
	return "direct (/etc/resolv.conf)"
}

// SetDNS backs up resolv.conf and writes VPN DNS servers.
// Refuses to overwrite if another service (Tailscale, resolvconf, etc.) manages the file.
func (b *DirectBackend) SetDNS(ifIndex int, servers []net.IP) error {
	// Safety check: don't overwrite resolv.conf if another service manages it
	if owner := resolvConfOwner(); owner != "" {
		return fmt.Errorf("resolv.conf is managed by %s — cannot safely overwrite. "+
			"Use a DNS backend that integrates with your network stack", owner)
	}

	// Backup current resolv.conf
	data, err := os.ReadFile(resolvConf)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("read resolv.conf: %w", err)
	}
	if len(data) > 0 {
		if err := os.WriteFile(resolvBackup, data, 0644); err != nil {
			return fmt.Errorf("backup resolv.conf: %w", err)
		}
		b.backedUp = true
	}

	// Write new resolv.conf with VPN DNS
	var sb strings.Builder
	sb.WriteString("# Generated by pVPN - will be restored on disconnect\n")
	for _, ip := range servers {
		fmt.Fprintf(&sb, "nameserver %s\n", ip.String())
	}

	if err := os.WriteFile(resolvConf, []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("write resolv.conf: %w", err)
	}

	return nil
}

// RevertDNS restores the original resolv.conf from backup.
// Checks for the backup file on disk (not just in-memory state) so this
// works correctly after a daemon restart where in-memory state is lost.
func (b *DirectBackend) RevertDNS(ifIndex int) error {
	data, err := os.ReadFile(resolvBackup)
	if err != nil {
		// No backup file on disk — nothing to restore
		return nil
	}

	if err := os.WriteFile(resolvConf, data, 0644); err != nil {
		return fmt.Errorf("restore resolv.conf: %w", err)
	}

	os.Remove(resolvBackup)
	b.backedUp = false
	return nil
}

// resolvConfOwner checks if resolv.conf is managed by another service.
// Returns the service name if managed, or empty string if safe to write.
func resolvConfOwner() string {
	data, err := os.ReadFile(resolvConf)
	if err != nil {
		return ""
	}
	content := string(data)

	// Check for common management signatures
	switch {
	case strings.Contains(content, "generated by tailscale"),
		strings.Contains(content, "tailscale"):
		return "Tailscale"
	case strings.Contains(content, "generated by resolvconf"):
		return "resolvconf"
	case strings.Contains(content, "generated by systemd-resolved"):
		return "systemd-resolved"
	case strings.Contains(content, "generated by NetworkManager"):
		return "NetworkManager"
	}

	// Check if it's a symlink (e.g., to systemd-resolved stub)
	if target, err := os.Readlink(resolvConf); err == nil {
		if strings.Contains(target, "systemd") {
			return "systemd-resolved (symlink)"
		}
		if strings.Contains(target, "resolvconf") {
			return "resolvconf (symlink)"
		}
	}

	return ""
}
